<link rel="stylesheet" href="public/css/Customers.css">
<h1>Clients avec leur factures associés</h1>
<table>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Code postal</th>
    <th>Ville</th>
    <th>Email</th>
    <th>Telephone</th>
    <th></th>
    <th></th>
    <?php foreach ($result as $res) : ?>
        <tr class="customer">
            <td><?= $res["nom"] ?></td>
            <td><?= $res["prenom"] ?></td>
            <td><?= $res["code_postal"] ?></td>
            <td><?= $res["ville"] ?></td>
            <td><?= $res["email"] ?></td>
            <td><?= $res["telephone"] ?></td>
            <td><a href="/Back-end/ECF/Factures/showFactures/<?= $res["id"] ?>"><img src="public/assets/file-lines-solid.svg" alt="icône lignes"></a></td>
            <td><a href="/Back-end/ECF/Factures/createFacture/<?= $res["id"] ?>"><img src="public/assets/square-plus-solid.svg" alt="icône plus"></a></td>
        </tr>
    <?php endforeach; ?>
</table>