<link rel="stylesheet" href="public/css/Customers.css">
<table>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Code postal</th>
    <th>Ville</th>
    <th>Email</th>
    <th>Telephone</th>
    <th></th>
    <th></th>
    <?php foreach ($result as $res) : ?>
        <tr class="customer">
            <td><?= $res["nom"] ?></td>
            <td><?= $res["prenom"] ?></td>
            <td><?= $res["code_postal"] ?></td>
            <td><?= $res["ville"] ?></td>
            <td><?= $res["email"] ?></td>
            <td><?= $res["telephone"] ?></td>
            <td><a href="http://localhost/Back-end/ECF/Factures/facture/<?= $res["id"] ?>">Toutes ces factures</a></td>
            <td><a href="http://localhost/Back-end/ECF/Factures/facture/<?= $res["id"] ?>">Nouvelle facture</a></td>
        </tr>
    <?php endforeach; ?>
</table>