<link rel="stylesheet" href="public/css/Factures.css">
<h1>Entrer chaque produits et leurs quantités pour générer la facture</h1>
<form action="/Back-end/ECF/Produits/ajoutProduitsPost" method="POST">
    <a href="" class="ajout_ligne">Ajouter une nouvelle ligne de produit</a>
    <div class="ligne_produit">
    </div>
    <input type="submit" value="Valider la facture">

</form>
<script src="public/javascript/Factures.js"></script>