<link rel="stylesheet" href="public/css/Index.css">
<h1>Bienvenue, veuillez vous connecter</h1>
<form action="/Back-end/ECF/Users/indexPost" method="POST">
    <input type="text" name="name" id="" placeholder="nom">
    <input type="password" name="password" id="" placeholder="mot de passe">
    <input type="submit" value="Connexion">
    <?php
    if (isset($erreur)) {
        echo "<p style='color:red'>$erreur</p>";
    }
    ?>
</form>