<link rel="stylesheet" href="public/css/Ventes.css">
<h2>Ventes du jour</h2>
<section class="order-details">
    <table>
        <thead>
            <tr>
                <th>Nombre de ventes</th>
                <th>Prix Total HT</th>
                <th>Prix Total TCC</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td><?= $resultD["nombre"] ?></td>
                <td><?= $resultD["total_ht"] ?> €</td>
                <td><?= $resultD["total_ttc"] ?> €</td>
            </tr>
        </tbody>
    </table>
</section>