<link rel="stylesheet" href="public/css/Ventes.css">
<h2>Ventes sur le mois en cours</h2>
<section class="order-details">
    <table>
        <thead>
            <tr>
                <th>Nombre de ventes</th>
                <th>Prix Total HT</th>
                <th>Prix Total TCC</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td><?= $resultM["nombre"] ?></td>
                <td><?= $resultM["total_ht"] ?> €</td>
                <td><?= $resultM["total_ttc"] ?> €</td>
            </tr>
        </tbody>
    </table>
</section>
<h2>Ventes sur l'année en cours</h2>
<section class="order-details">
    <table>
        <thead>
            <tr>
                <th>Nombre de ventes</th>
                <th>Prix Total HT</th>
                <th>Prix Total TCC</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td><?= $resultY["nombre"] ?></td>
                <td><?= $resultY["total_ht"] ?> €</td>
                <td><?= $resultY["total_ttc"] ?> €</td>
            </tr>
        </tbody>
    </table>
</section>